# Generated by Django 4.2.7 on 2024-11-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("arabic", models.TextField()),
                ("english", models.TextField()),
            ],
        ),
    ]
